# Generated by Django 3.2.10 on 2021-12-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
